Enabled wild-card support ("*") for the environment name  (#16)
* Enabled wild-card support ("*") for the environment name in the env_config.yaml file

* Fixed formatting in proton_run file

* Fixed indentation in proton_run

* Refactored the if-then-else statements

* Removed typos from README

diff --git a/.github/workflows/proton_run.yml b/.github/workflows/proton_run.yml
--- a/.github/workflows/proton_run.yml
+++ b/.github/workflows/proton_run.yml
@@ -121,21 +121,26 @@ jobs:
           working_directory=pipeline/$service_name
         fi
 
-        if [[ $(jq -r --arg env $environment_name 'has($env)' env_config.json) = "false" ]]; then
-          echo "Missing $environment_name from env_config.json, exiting"
-          exit 1
+        if [[ $(jq -r --arg env $environment_name 'has($env)' env_config.json) = "true" ]]; then
+          role_arn=$(jq -r --arg env $environment_name '.[$env]["role"]' env_config.json)
+          target_region=$(jq -r --arg env $environment_name '.[$env]["region"]' env_config.json)
+          state_bucket=$(jq -r --arg env $environment_name '.[$env]["state_bucket"]' env_config.json)   
+        else     
+          if [[ $(jq -r --arg env $environment_name 'has("*")' env_config.json) = "true" ]]; then
+            role_arn=$(jq -r --arg env $environment_name '.["*"]["role"]' env_config.json)
+            target_region=$(jq -r --arg env $environment_name '.["*"]["region"]' env_config.json)
+            state_bucket=$(jq -r --arg env $environment_name '.["*"]["state_bucket"]' env_config.json)
+          else
+            echo "Missing $environment_name or * from env_config.json, exiting"
+            exit 1
+          fi
         fi
-
+        
         echo "::set-output name=working_directory::$working_directory"
         echo "::set-output name=environment::$environment_name"
         
-        role_arn=$(jq -r --arg env $environment_name '.[$env]["role"]' env_config.json)
         echo "::set-output name=role_arn::$role_arn"
-
-        target_region=$(jq -r --arg env $environment_name '.[$env]["region"]' env_config.json)
         echo "::set-output name=target_region::$target_region"
-
-        state_bucket=$(jq -r --arg env $environment_name '.[$env]["state_bucket"]' env_config.json)
         echo "::set-output name=state_bucket::$state_bucket"
 
   terraform:
