Few more sample fixes (#7)
* Remove dependency on terraform.yml

* proton_run should run on create pull request as well as push to main

* Update proton_run.yml

* Fix working-directory typo

* Update proton_run.yml

* Update requested for Proton - environment/my_new_tf_env

* Update requested for Proton - environment/my_new_tf_env

* Update proton_run.yml

* Update requested for Proton - environment/my_new_tf_env

* Update proton_run.yml

* Update requested for Proton - environment/my_new_tf_env

* Update proton_run.yml

* Update proton_run.yml

* Update requested for Proton - environment/my_new_tf_env

* Update proton_run.yml

* Update requested for Proton - environment/my_new_tf_env

* Update proton_run.yml

* Update requested for Proton - environment/my_new_tf_env

* Delete terraform.yml

* Update requested for Proton - environment/my_new_tf_env

* Update proton_run.yml

* Delete my_new_tf_env directory

Co-authored-by: sbx_user1051 <sbx_user1051@169.254.244.253>
Co-authored-by: sbx_user1051 <sbx_user1051@169.254.113.33>
Co-authored-by: sbx_user1051 <sbx_user1051@169.254.114.13>
Co-authored-by: sbx_user1051 <sbx_user1051@169.254.249.125>
Co-authored-by: sbx_user1051 <sbx_user1051@169.254.157.49>
Co-authored-by: sbx_user1051 <sbx_user1051@169.254.139.233>
Co-authored-by: sbx_user1051 <sbx_user1051@169.254.48.97>
Co-authored-by: sbx_user1051 <sbx_user1051@169.254.95.85>

diff --git a/.github/workflows/proton_run.yml b/.github/workflows/proton_run.yml
--- a/.github/workflows/proton_run.yml
+++ b/.github/workflows/proton_run.yml
@@ -4,6 +4,12 @@
 name: 'proton-run'
 
 on:
+  pull_request:
+    types:
+      - opened
+      - reopened
+    paths:
+      - '**/.proton/deployment-metadata.json'
   push:
     branches:
       - main
@@ -18,10 +24,11 @@ jobs:
     outputs:
       role_arn: ${{ steps.get-data.outputs.role_arn }}
       environment: ${{ steps.get-data.outputs.environment }}
-      resource-arn: ${{ steps.get-data.outputs.resource-arn }}
-      working-directory: ${{ steps.get-data.outputs.working-directory }}
-      deployment-id: ${{ steps.get-data.outputs.deployment-id }}
-      aws_region: ${{ steps.get-data.outputs.aws_region }}
+      resource_arn: ${{ steps.get-data.outputs.resource_arn }}
+      working_directory: ${{ steps.get-data.outputs.working_directory }}
+      deployment_id: ${{ steps.get-data.outputs.deployment_id }}
+      target_region: ${{ steps.get-data.outputs.target_region }}
+      proton_region: ${{ steps.get-data.outputs.proton_region }}
       state_bucket: ${{ steps.get-data.outputs.state_bucket }}
     
     permissions:
@@ -63,10 +70,15 @@ jobs:
       id: get-data
       run: |
         modified_resource_arn=$(jq -r '.resourceMetadata.arn' ${{ steps.find-modified.outputs.deployment-metadata-path }})
-        echo "::set-output name=resource-arn::$modified_resource_arn"
+        echo "::set-output name=resource_arn::$modified_resource_arn"
+        
+        IFS=':'
+        read -a split_arn <<< "$modified_resource_arn"
+        proton_region=${split_arn[3]}
+        echo "::set-output name=proton_region::$proton_region"
 
         deployment_id=$(jq -r '.deploymentId' ${{ steps.find-modified.outputs.deployment-metadata-path }})
-        echo "::set-output name=deployment-id::$deployment_id"
+        echo "::set-output name=deployment_id::$deployment_id"
 
         if [[ "$modified_resource_arn" == *":environment/"* ]]; then
           environment_name=${modified_resource_arn##*/}
@@ -100,26 +112,115 @@ jobs:
           exit 1
         fi
 
-        echo "::set-output name=working-directory::$working_directory"
+        echo "::set-output name=working_directory::$working_directory"
         echo "::set-output name=environment::$environment_name"
         
         role_arn=$(jq -r --arg env $environment_name '.[$env]["role"]' env_config.json)
         echo "::set-output name=role_arn::$role_arn"
 
-        aws_region=$(jq -r --arg env $environment_name '.[$env]["region"]' env_config.json)
-        echo "::set-output name=aws_region::$aws_region"
+        target_region=$(jq -r --arg env $environment_name '.[$env]["region"]' env_config.json)
+        echo "::set-output name=target_region::$target_region"
 
         state_bucket=$(jq -r --arg env $environment_name '.[$env]["state_bucket"]' env_config.json)
         echo "::set-output name=state_bucket::$state_bucket"
-    
-  call-terraform-workflow:
+
+  terraform:
+    name: 'Terraform'
     needs: get-deployment-data
-    uses: awishn02/aws-proton-terraform-github-actions-sample/.github/workflows/terraform.yml@main
-    with:
-      role_arn: ${{ needs.get-deployment-data.outputs.role_arn }}
-      environment: ${{ needs.get-deployment-data.outputs.environment }}
-      resource_arn: ${{ needs.get-deployment-data.outputs.resource-arn }}
-      working_directory: ${{ needs.get-deployment-data.outputs.working-directory }}
-      deployment_id: ${{ needs.get-deployment-data.outputs.deployment-id }}
-      aws_region: ${{ needs.get-deployment-data.outputs.aws_region }}
-      state_bucket: ${{ needs.get-deployment-data.outputs.state_bucket }}
+    runs-on: ubuntu-latest
+    environment: ${{ needs.get-deployment-data.outputs.environment }}
+    permissions:
+      id-token: write
+      contents: read
+    
+    defaults:
+      run:
+        working-directory: ${{ needs.get-deployment-data.outputs.working_directory }}
+        shell: bash # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
+
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v2
+      continue-on-error: true
+    
+    - name: Configure AWS Credentials
+      id: assume_role
+      uses: aws-actions/configure-aws-credentials@v1
+      with:
+        aws-region: ${{ needs.get-deployment-data.outputs.target_region }}
+        role-to-assume: ${{ needs.get-deployment-data.outputs.role_arn }}
+        role-session-name: TF-Github-Actions
+      continue-on-error: false
+
+    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+    - name: Setup Terraform
+      id: tf_setup
+      uses: hashicorp/setup-terraform@v1
+      with:
+        terraform_version: 1.0.7
+        terraform_wrapper: false
+      continue-on-error: true
+
+    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+    - name: Terraform Init
+      id: tf_init
+      run: terraform init -backend-config="bucket=${{ needs.get-deployment-data.outputs.state_bucket }}" -backend-config="key=${{ needs.get-deployment-data.outputs.working_directory }}terraform.tfstate" -backend-config="region=${{ needs.get-deployment-data.outputs.target_region }}"
+      continue-on-error: true
+
+    # Checks that all Terraform configuration files adhere to a canonical format
+    - name: Terraform Format
+      id: tf_fmt
+      run: terraform fmt -diff -check
+      continue-on-error: true
+
+    # Generates an execution plan for Terraform
+    - name: Terraform Plan
+      id: tf_plan
+      run: terraform plan -var="aws_region=${{ needs.get-deployment-data.outputs.target_region }}"
+      continue-on-error: true
+
+    # On push to main, build or change infrastructure according to Terraform configuration files
+    # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
+    - name: Terraform Apply
+      id: tf_apply
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      run: terraform apply -auto-approve -var="aws_region=${{ needs.get-deployment-data.outputs.target_region }}"
+      continue-on-error: true
+
+    # This is a temporary measure until this feature exits Public Preview
+    - name: Install Proton Model
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+      run: |
+        aws s3 cp s3://aws-proton-preview-public-files/model/proton-2020-07-20.normal.json  .
+        aws configure add-model --service-model "file://proton-2020-07-20.normal.json" --service-name proton
+
+    - name: Notify Proton Success
+      id: notify_success
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && steps.tf_apply.outcome == 'success'
+      continue-on-error: true
+      run: |
+        # Get outputs as json
+        outputs_json=$(terraform output -json)
+
+        # The outputs parameters expects a list of key=keyName,valueString=value key=key2Name,valueString=value2 etc...
+        # So here we convert the output json into a shell array
+        # NOTE: This will probably not play nicely with complex output objects (non primitives)
+
+        formatted_outputs=( $(echo $outputs_json | jq -r "to_entries|map(\"key=\(.key),valueString=\(.value.value|tostring)\")|.[]") )
+
+        # Notify proton
+        aws proton notify-resource-deployment-status-change --region ${{ needs.get-deployment-data.outputs.proton_region }} --resource-arn ${{ needs.get-deployment-data.outputs.resource_arn }} --status SUCCEEDED --deployment-id ${{ needs.get-deployment-data.outputs.deployment_id }} --outputs $formatted_outputs
+        echo "Notify success!"   
+        
+    - name: Notify Proton Failure
+      if: github.ref == 'refs/heads/main' && github.event_name == 'push' && (steps.tf_apply.outcome != 'success' || steps.notify_success.outcome != 'success')
+      run: |
+        aws proton notify-resource-deployment-status-change --region ${{ needs.get-deployment-data.outputs.proton_region }} --resource-arn ${{ needs.get-deployment-data.outputs.resource_arn }} --status FAILED --deployment-id ${{ needs.get-deployment-data.outputs.deployment_id }}
+        echo "Notify failure!"
+    
+    # When running in response to a pull request, we are just validating the terraform is okay, this will force the workflow to fail if it's not.
+    - name: Check for validation failures
+      if: github.event_name == 'pull_request' && (steps.assume_role.outcome != 'sucess' || steps.tf_setup.outcome != 'success' || steps.tf_init.outcome != 'success' || steps.tf_fmt.outcome != 'success' || steps.tf_plan.outcome != 'success')
+      run: exit 1
+        
